"""add subscription_discount

Revision ID: 455faa336100
Revises: 6f737b3c9586
Create Date: 2026-03-09 19:15:22.662392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455faa336100'
down_revision: Union[str, Sequence[str], None] = '6f737b3c9586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applied_discount', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('applied_discount')

    with op.batch_alter_table('inventory_config', schema=None) as batch_op:
        batch_op.drop_column('subscription_discount_percentage')

    # ### end Alembic commands ###
