"""add min_duration

Revision ID: 75966e4fa446
Revises: 455faa336100
Create Date: 2026-03-09 19:26:32.248132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75966e4fa446'
down_revision: Union[str, Sequence[str], None] = '455faa336100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_subscription_duration_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_duration_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('min_duration_days')

    with op.batch_alter_table('inventory_config', schema=None) as batch_op:
        batch_op.drop_column('min_subscription_duration_days')

    # ### end Alembic commands ###
