"""add system_config

Revision ID: 75a3f4028623
Revises: cf2d6e4e6047
Create Date: 2026-04-06 17:50:35.742615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '75a3f4028623'
down_revision: Union[str, Sequence[str], None] = 'cf2d6e4e6047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_field_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_field_definitions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_field_definitions_name'), ['name'], unique=True)

    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('store_addresses', sa.JSON(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('sinpe_number', sa.String(), nullable=True),
    sa.Column('customer_service_phone', sa.String(), nullable=True),
    sa.Column('enable_subscriptions', sa.Boolean(), nullable=False),
    sa.Column('enable_marketing', sa.Boolean(), nullable=False),
    sa.Column('subscription_discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_subscription_duration_days', sa.Integer(), nullable=True),
    sa.Column('currency_symbol', sa.String(), nullable=True),
    sa.Column('country_phone_code', sa.String(), nullable=True),
    sa.Column('company_icon_class', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_config_id'), ['id'], unique=False)

    with op.batch_alter_table('inventory_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_config_id'))

    op.drop_table('inventory_config')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_fields', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('custom_fields')

    op.create_table('inventory_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('business_name', sa.VARCHAR(), nullable=True),
    sa.Column('store_addresses', sqlite.JSON(), nullable=True),
    sa.Column('account_number', sa.VARCHAR(), nullable=True),
    sa.Column('sinpe_number', sa.VARCHAR(), nullable=True),
    sa.Column('customer_service_phone', sa.VARCHAR(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('subscription_discount_percentage', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('min_subscription_duration_days', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_config_id'), ['id'], unique=False)

    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_config_id'))

    op.drop_table('system_config')
    with op.batch_alter_table('product_field_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_field_definitions_name'))
        batch_op.drop_index(batch_op.f('ix_product_field_definitions_id'))

    op.drop_table('product_field_definitions')
    # ### end Alembic commands ###
