"""Add AI configs and AILog

Revision ID: b9855ac2200a
Revises: de56a9a6cc32
Create Date: 2026-04-06 19:31:39.909236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9855ac2200a'
down_revision: Union[str, Sequence[str], None] = 'de56a9a6cc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_logs_customer_phone'), ['customer_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_system_prompt', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('google_gemini_api_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ai_model_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_column('ai_model_name')
        batch_op.drop_column('google_gemini_api_key')
        batch_op.drop_column('ai_system_prompt')

    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_logs_id'))
        batch_op.drop_index(batch_op.f('ix_ai_logs_customer_phone'))

    op.drop_table('ai_logs')
    # ### end Alembic commands ###
